# Tag format. All color codes possible, use %tag% in place of the actual tag
tag_format: '&a[&f%tag%&a]&r '
# Maximum length of tag. If set to 0, max length disabled  
max_tag_length: 0
# Allow tags to have their own color codes
allow_tag_colors: true
# Disallowed tag content. if any one or more of these words are found
# in a tag, the user will be asked to choose a different tag.
disallowed_tags:
  - admin
  - mod
# Strips any special characters from tag. Recommended. (will leave in &)
alphanumeric_only: true
