name: NewTag
version: 1.0.1
main: net.darqy.NewTag.NewTag
author: Darqy
description: Put tags on players that are independent of other chat/permissions
commands:
  newtag:
    description: Control NewTag
    usage: /<command> <args>
    aliases: [tag, nt]
permissions:
  newtag.admin:
    description: Allows usage of /donate
    default: op
